"""remove old tables

Revision ID: 2c8aeabffcc8
Revises: b8362f0b3760
Create Date: 2026-06-17 10:17:25.940114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8aeabffcc8'
down_revision: Union[str, Sequence[str], None] = 'b8362f0b3760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('DROP TABLE IF EXISTS exam')
    op.execute('DROP TABLE IF EXISTS teacher')
    op.execute('DROP TABLE IF EXISTS perf_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perf_test',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(collation='C'), autoincrement=False, nullable=True),
    sa.Column('annotation', sa.TEXT(collation='C'), autoincrement=False, nullable=True)
    )
    op.create_table('teacher',
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('exam',
    sa.Column('exam_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('exam_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('exam_date', sa.DATE(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
