"""update table columns

Revision ID: 4362b7067e26
Revises: fb80c6a827c3
Create Date: 2026-04-20 21:53:07.072065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4362b7067e26'
down_revision: Union[str, Sequence[str], None] = 'fb80c6a827c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('biography', sa.String(), nullable=False))
    op.add_column('authors', sa.Column('birth_date', sa.DateTime(), nullable=False))
    op.add_column('authors', sa.Column('nationality', sa.String(), nullable=False))
    op.add_column('books', sa.Column('page_count', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('genre', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('description', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('duration_hours', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('email', sa.String(), nullable=False))
    op.add_column('students', sa.Column('phone', sa.String(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    op.drop_column('users', 'email')
    op.drop_column('students', 'phone')
    op.drop_column('students', 'email')
    op.drop_column('students', 'age')
    op.drop_column('courses', 'duration_hours')
    op.drop_column('courses', 'description')
    op.drop_column('books', 'genre')
    op.drop_column('books', 'page_count')
    op.drop_column('authors', 'nationality')
    op.drop_column('authors', 'birth_date')
    op.drop_column('authors', 'biography')
    # ### end Alembic commands ###
