"""add pending_order_confirmations table

Revision ID: ad1e3cc88a2e
Revises: 2c8aeabffcc8
Create Date: 2026-07-07 12:55:26.394563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad1e3cc88a2e'
down_revision: Union[str, Sequence[str], None] = 'b8362f0b3760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('DROP TABLE IF EXISTS exam')
    op.execute('DROP TABLE IF EXISTS teacher')
    op.execute('DROP TABLE IF EXISTS perf_test')

    op.create_table('pending_order_confirmations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_order_confirmations')
    op.create_table('perf_test',
                    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('reason', sa.TEXT(collation='C'), autoincrement=False, nullable=True),
                    sa.Column('annotation', sa.TEXT(collation='C'), autoincrement=False, nullable=True)
                    )
    op.create_table('teacher',
                    sa.Column('teacher_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True),
                    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True)
                    )
    op.create_table('exam',
                    sa.Column('exam_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('exam_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
                    sa.Column('exam_date', sa.DATE(), autoincrement=False, nullable=True)
                    )
    # ### end Alembic commands ###
